name: meesign_core
description: Core layer of MeeSign client shared by GUI and CLI.
version: 0.1.1
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  collection: ^1.16.0
  meesign_native: {path: ../meesign_native}
  meesign_network: {path: ../meesign_network}
  meta: ^1.7.0
  path: ^1.8.1
  rxdart: ^0.27.5
  synchronized: ^3.0.0+3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
